[2025-09-16T10:59:32.156+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/google_sheet_trigger_dag.py
[2025-09-16T10:59:32.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/google_sheet_trigger_dag.py for tasks to queue
[2025-09-16T10:59:32.205+0000] {logging_mixin.py:188} INFO - [2025-09-16T10:59:32.192+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/google_sheet_trigger_dag.py
[2025-09-16T10:59:32.442+0000] {logging_mixin.py:188} INFO - [2025-09-16T10:59:32.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_sheet_trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/google_sheet_trigger_dag.py", line 3, in <module>
    from airflow.providers.google.suite.hooks.sheets import GoogleSheetsHook
ImportError: cannot import name 'GoogleSheetsHook' from 'airflow.providers.google.suite.hooks.sheets' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/suite/hooks/sheets.py)
[2025-09-16T10:59:32.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/google_sheet_trigger_dag.py
[2025-09-16T10:59:32.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/google_sheet_trigger_dag.py took 0.595 seconds
